---
# handlers file for php-fpm_pool

# For some reason centminmod doesn't work unless both are restarted
- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: restart php-fpm
  service: name=php-fpm state=restarted
